### ISSUE TITLE
Crash on startup - YeOldeTanks

### ISSUE THREAD

**Issue by strates** [DoughnutTeam/ProjectGreg#3]
Relevant lines from the crashlog:

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: net.shadowfacts.yeoldetanks.YeOldeTanks

java.lang.UnsupportedClassVersionError: net/shadowfacts/yeoldetanks/YeOldeTanks : Unsupported major.minor version 52.0

Full log:
[crash-2015-10-13_23.22.19-client.txt](https://github.com/DoughnutTeam/ProjectGreg/files/12846/crash-2015-10-13_23.22.19-client.txt)

**Comment by DoughnutDev** [comment]
I will be fixing this in a hot fix.

**Comment by DoughnutDev** [comment]
Java 8 is required.
