### ISSUE TITLE
Wrought Iron Plate for LV Machine Hull

### ISSUE THREAD

**Issue by zeromic** [DoughnutTeam/ProjectGreg#5]
Hi, 

I searched NEI but I couldn't find any method to create them. Without them i cannot progress to gregtech LV tier.

additional Infos:
gregtech iron nuggets can be smelted in Wrought Iron nuggets, but nuggets cannot crafted to ingots

iron ingots have to be smeltered into nuggets to get gregtech iron nuggets.. normal crafting 1x iron ingot> 9 nuggets yield tinkers nuggets which wont smelt into Wrought Iron nuggets

**Comment by DoughnutDev** [comment]
So I added a recipe that uses 9 wrought iron nuggets to make a wrought iron bar. The smeltery issue can not be fixed due to wrought iron having a liquid form.
