### ISSUE TITLE
Rotarycraft Lubricant bucket not working

### ISSUE THREAD

**Issue by zeromic** [DoughnutTeam/ProjectGreg#7]
You cannot bucket Lubricant from Rotarycraft. Not with Buckets in the Grinder GUI or by Right-Clicking Tanks/ Reservoirs with a bucket in hand.

You can still apply it to gearboxes with fluid pipes and lubricant Hose but its more challenging and NEI shows the Lubricant Bucket from Rotarycraft avalible.

**Comment by DoughnutDev** [comment]
I was having this same issue and I was told it had a bucket form due to it being in the Liquid Ore Dictionary, and I kinda like it being harder because RotaryCraft should be a challenge. Also what is your IGN, and we do have a server if you ever want to play on it.
